# Generated by Django 5.2 on 2025-04-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField()),
            ],
            options={
                'db_table': 'exemplo',
                'managed': False,
            },
        ),
    ]
