# Generated by Django 5.2 on 2025-04-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binance_bot', '0002_tradeorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exemplo',
        ),
    ]
