name: Build and deploy Django app to Azure Web App - projeto-cloud-binance

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Alterado para uma versão estável

      - name: Criar e ativar ambiente virtual
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Coletar arquivos estáticos do Django
        run: |
          cd project_cloud_binance
          python manage.py collectstatic --noinput

      - name: Criar arquivo de deploy
        run: |
          zip -r release.zip . -x "*.git*" "__pycache__/*" "venv/*"

      - name: Upload do artefato para o job de deploy
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Baixar o artefato do job de build
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Descompactar o artefato
        run: unzip release.zip -d $GITHUB_WORKSPACE

      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8D1B6C4A86A941FDB077FA3533DF0A5A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A8B4229EF66342989B707F59381FEEF7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AE898FD7A0E14BD8935B8ADC805D04E1 }}

      - name: Fazer deploy no Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'projeto-cloud-binance'
          slot-name: 'Production'
          package: .

      